### ISSUE TITLE
Use dataclasses with local_zone

### ISSUE THREAD

**Issue by enchant97** [dmachard/python-unbound-console#4]
It would be nice if `load_zone` would instead take a Python dataclass rather than a yaml string. This would cut down on the pyyaml pip requirement being needed.

If yaml functionality is still required, it for example could be moved into a separate method called `load_zone_yaml`, which would allow for the pip requirement to marked as an optional install for the users who want to use it. Also the loaded yaml data could be converted into a dataclass.

Example dataclass:

```python
from dataclasses import dataclass
from typing import List

@dataclass
class LocalZone:
    name: str
    type_: str = "static"
    records: List[str] = []
```

**Comment by enchant97** [comment]
Does that mean you will allow "load_zone" to take dataclass and a separate  "load_zone_yaml" function that takes in yaml? Or is it required to only have one function "load_zone"?

**Comment by dmachard** [comment]
Just for backwards compatibility,
can you kept the load_zone like that and create a new one for the dataclass support ?

**Comment by enchant97** [comment]
I can make the `load_zone` method take both yaml and the dataclass. That would keep the backwards compatibility.

Also is it possible to make the pyyaml requirement optional, so if you wanted yaml support you would install the pip package like this: `pip install unbound_console[yaml]`?

**Comment by dmachard** [comment]
good for me if some documentations exits :)
